module SkelGengo where

-- Haskell module generated by the BNF converter

import AbsGengo
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transProgram :: Show a => Program a -> Result
transProgram x = case x of
  Program _ topdefs -> failure x
transTopDef :: Show a => TopDef a -> Result
transTopDef x = case x of
  FnDef _ ident args type_ block -> failure x
  GnDef _ ident args type_ block -> failure x
transArg :: Show a => Arg a -> Result
transArg x = case x of
  VArg _ type_ ident -> failure x
  RefArg _ type_ ident -> failure x
transBlock :: Show a => Block a -> Result
transBlock x = case x of
  Block _ stmts -> failure x
transStmt :: Show a => Stmt a -> Result
transStmt x = case x of
  Empty _ -> failure x
  BStmt _ block -> failure x
  Init _ type_ ident expr -> failure x
  Ass _ ident expr -> failure x
  Ret _ expr -> failure x
  Yield _ expr -> failure x
  Break _ -> failure x
  Continue _ -> failure x
  Cond _ if_ -> failure x
  While _ expr block -> failure x
  For _ ident expr block -> failure x
  SExp _ expr -> failure x
  NestFn _ topdef -> failure x
transIf :: Show a => If a -> Result
transIf x = case x of
  If _ expr block -> failure x
  IfElse _ expr block else_ -> failure x
transElse :: Show a => Else a -> Result
transElse x = case x of
  ElseBlock _ block -> failure x
  ElseIf _ if_ -> failure x
transType :: Show a => Type a -> Result
transType x = case x of
  Int _ -> failure x
  Str _ -> failure x
  Bool _ -> failure x
  Generator _ type_ -> failure x
transExpr :: Show a => Expr a -> Result
transExpr x = case x of
  EVar _ ident -> failure x
  ELitInt _ integer -> failure x
  ELitTrue _ -> failure x
  ELitFalse _ -> failure x
  EApp _ ident exprs -> failure x
  EString _ string -> failure x
  Neg _ expr -> failure x
  Not _ expr -> failure x
  EMul _ expr1 mulop expr2 -> failure x
  EAdd _ expr1 addop expr2 -> failure x
  ERel _ expr1 relop expr2 -> failure x
  EAnd _ expr1 expr2 -> failure x
  EOr _ expr1 expr2 -> failure x
transAddOp :: Show a => AddOp a -> Result
transAddOp x = case x of
  Plus _ -> failure x
  Minus _ -> failure x
transMulOp :: Show a => MulOp a -> Result
transMulOp x = case x of
  Times _ -> failure x
  Div _ -> failure x
  Mod _ -> failure x
transRelOp :: Show a => RelOp a -> Result
transRelOp x = case x of
  LTH _ -> failure x
  LE _ -> failure x
  GTH _ -> failure x
  GE _ -> failure x
  EQU _ -> failure x
  NE _ -> failure x

